/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import java.util.ArrayList;
import java.util.Map;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        Map<String, ArrayList<String>> inputData = FileInput.main();

        System.out.println(inputData.get("left"));
        System.out.println(inputData.get("right"));
        Integer totalDistance = PointDistance.main(inputData.get("left"), inputData.get("right"));
        System.out.println("Total Distance Calculated!");
        System.out.println("It is! " + totalDistance);
    }
}
